config/routes.rb
Rails.application.routes.draw do


  class WalletoneMiddleware < Walletone::Middleware::Base
    def perform notify, env
      raise 'Wrong signature' unless notify.valid? Settings.w1.signature
        u = User.find(notify.WMI_DESCRIPTION.to_i)
        u.money = u.money+notify.WMI_PAYMENT_AMOUNT.to_i
        pay=Payment.new user_id: notify.WMI_DESCRIPTION.to_i, amount: notify.WMI_PAYMENT_AMOUNT.to_f, order_id: notify.fetch(:WMI_ORDER_ID)
        if pay.valid? and u.valid?
          pay.save!
          u.save!
          'Return some message for OK response'
        else
         raise 'Not saved'
        end
    end
  end

  # match '*path', via: :all, to: 'home#error_404'
  mount WalletoneMiddleware.new => '/w1_callback'

  # scope :unitpay do
  #   get :success, to: 'unitpay#success'
  #   get :fail, to: 'unitpay#fail'
  #   get :notify, to: 'unitpay#notify'
  # end

  post 'cabinet/edit_auto_extension', to: 'cabinet#edit_auto_extension', as: 'cabinet_edit_auto_extension'
  post 'cabinet/free_dns', to: 'cabinet#free_dns', as: 'cabinet_free_dns'
  get 'cabinet/pay', to: 'cabinet#pay', as: 'cabinet_pay'
  get 'cabinet/new', to: 'cabinet#new', as: 'cabinet_new'
  post 'cabinet/create', to: 'cabinet#create', as: 'cabinet_create'
  delete 'cabinet/:id', to: 'cabinet#destroy', as: 'cabinet_destroy'
  get 'cabinet', to: 'cabinet#home', as: 'cabinet_home'
  get 'cabinet/extend/:id', to: 'cabinet#extend', as: 'cabinet_extend'
  post 'cabinet/extend_up/:id', to: 'cabinet#extend_up'
  post 'cabinet/work/:id', to: 'cabinet#work', as: 'cabinet_work'
  get 'cabinet/edit/:id', to: 'cabinet#edit', as: 'cabinet_edit'
  post 'cabinet/update/:id', to: 'cabinet#update', as: 'cabinet_update'
  get 'cabinet/backups/:id', to: 'cabinet#backups', as: 'cabinet_backups'
  post 'cabinet/create_backup'
  post 'cabinet/delete_backup'
  post 'cabinet/apply_backup'
  get 'cabinet/token/:id', to: 'cabinet#token', as: 'cabinet_token'
  post 'cabinet/create_token', to: 'cabinet#create_token', as: 'cabinet_create_token'
  post 'cabinet/delete_token', to: 'cabinet#delete_token', as: 'cabinet_delete_token'
  post 'cabinet/reset_permissions/:id', to: 'cabinet#reset_permissions', as: 'cabinet_reset_permissions'
  get 'cabinet/settings/:id', to: 'cabinet#settings', as: 'cabinet_settings'
  post 'cabinet/settings_edit', to: 'cabinet#settings_edit', as: 'cabinet_settings_edit'
  # get 'cabinet/bans/:id', to: 'cabinet#bans', as: 'cabinet_bans'
  # post 'cabinet/ban', to: 'cabinet#ban', as: 'cabinet_ban'
  # post 'cabinet/unban', to: 'cabinet#unban', as: 'cabinet_unban'
  # post 'cabinet/unbanall', to: 'cabinet#unbanall', as: 'cabinet_unbanall'
  get 'cabinet/pay_redirect', to: 'cabinet#pay_redirect', as: 'cabinet_pay_redirect'
  get 'cabinet/ref', to: 'cabinet#ref', as: 'cabinet_ref'
  get 'cabinet/panel/:id', to: 'cabinet#panel', as: 'cabinet_panel'

  match '/ref/:ref' => 'home#ref', via: [:get, :post]
  get 'admin/info/:id', to: 'admin#info', as: 'admin_info'
  get 'admin/home'
  post 'admin/setmoney/:id', to: 'admin#setmoney'
  get 'admin/belongs_verification', to: 'admin#belongs_verification', as: 'admin_belongs_verification'
  get 'admin/user_list', to: 'admin#user_list', as: 'admin_user_list'
  get 'admin/servers', to: 'admin#servers', as: 'admin_servers'
  get 'admin/del_physical_server', to: 'admin#del_physical_server', as: 'admin_del_physical_server'
  get 'admin/amounts', to: 'admin#amounts', as: 'admin_amounts'
  post 'admin/destroy_payment', to: 'admin#destroy_payment', as: 'admin_destroy_payment'
  get 'admin/panel_tsserver/:id', to: 'admin#panel_tsserver', as: 'admin_panel_tsserver'
  post 'admin/update_panel_tsserver', to: 'admin#update_panel_tsserver', as: 'admin_update_panel_tsserver'


  root 'home#index'
  get '/home/regulations' => 'home#regulations', as: 'home_regulations'
  get 'home/index'
  get 'home/news'
  get '/home/how_buy' => 'home#how_buy', as: 'home_how_buy'

  devise_for :users, :controllers => {registrations: "registrations", passwords: "passwords", sessions: "sessions", omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/amounts.html.erb
<table class="server-list">
  <thead>
  <tr>
    <th>id</th>
    <th>user_id</th>
    <th>amount</th>
    <th>created_at</th>
    <th>order_id</th>

  </tr>
  </thead>

  <tbody>
  <% @amounts.each do |amounts| %>
      <tr>
        <td><%= amounts.id %></td>
        <td><%= amounts.user_id %></td>
        <td><%= amounts.amount %>руб.</td>
        <td><%= amounts.created_at %></td>
        <td><%= amounts.order_id %></td>
        <td><%= link_to 'Удалить', admin_destroy_payment_path(id: amounts.id), class: 'btn btn-danger', method: :post%></td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/admin/belongs_verification.html.erb
<h2>Список серверов не найденых в БД, но существующих на сервере</h2>
<table class="server-list">
  <thead>
    <tr>
      <th>machine_id</th>
      <th>name</th>
      <th>port</th>
      <th>status</th>
      <th>client_online</th>
      <th>max_clients</th>
      <th>auto_start</th>
    </tr>
  </thead>

<% @physical.each do |p| %>
  <tbody>
    <tr>
      <td><%= p["virtualserver_id"] %></td>
      <td><%= p["virtualserver_name"] %></td>
      <td><%= p["virtualserver_port"] %></td>
      <td><%= p["virtualserver_status"] %></td>
      <td><%= p["virtualserver_clientsonline"] %></td>
      <td><%= p["virtualserver_maxclients"] %></td>
      <td><%= p["virtualserver_autostart"] %></td>
    </tr>
  </tbody>
<% end %>

</table>



<h2>Список серверов не найденых на сервере, но существующих в БД </h2>
<table class="server-list">
<thead>
<tr>
  <th>ID</th>
  <th>port</th>
  <th>dns</th>
  <th>slots</th>
  <th>time_payment</th>
  <th>user_id</th>
  <th>machine_id</th>
  <th>state</th>
</tr>
</thead>
<% @logic.each do |l| %>
    <tbody>
    <tr>
      <td><%= l.id %></td>
      <td><%= l.port %></td>
      <td><%= l.dns %></td>
      <td><%= l.slots %></td>
      <td><%= l.time_payment %></td>
      <td><%= l.user_id %></td>
      <td><%= l.machine_id %></td>
      <td><%= l.state %></td>
    </tr>
    </tbody>
<% end %>

</table>

app/views/admin/home.html.erb
<style>
  .btn{
    width: 200px;
  }
</style>


<%= link_to 'Belongs verification', admin_belongs_verification_path, class: "btn btn-primary" %> <br>
<%= link_to 'User list', admin_user_list_path, class: "btn btn-primary"  %> <br>
<%= link_to 'Server list', admin_servers_path, class: "btn btn-primary"  %> <br>
<%= link_to 'Payments amount', admin_amounts_path, class: "btn btn-primary"  %> <br>

<h3>Quantity users: <%= @count_users %></h3>
<h3>Payment: <%= @count_spent %> </h3>

app/views/admin/info.html.erb
<h2><%= @user.email %></h2>

<%= form_tag "/admin/setmoney/#{@user.id}", method: :post do %>
    Баланс:<%= number_field_tag 'money', @user.money, class: :text_field, step: :any  %>
    <%= submit_tag 'Save', id: @user.id, remote:true %>
<% end %>

<table class="server-list">
  <thead>
  <tr>
    <th>ID</th>
    <th>Домен</th>
    <th>Кол-во слотов</th>
    <th>До какого оплачено</th>
    <th>user_id</th>
    <th>machine_id</th>
    <th>Дата создания</th>
    <th>Дата редактирования</th>
    <th>state</th>

  </tr>
  </thead>

  <tbody>
  <% @user.tsservers.each do |ts| %>
      <tr>
        <td><%= ts.id %></td>
        <td><%= ts.dns+'.'+Settings.other.dns unless ts.dns.empty? %></td>
        <td><%= ts.slots %></td>
        <td><%= ts.time_payment %></td>
        <td><%= ts.user_id %></td>
        <td><%= ts.machine_id %></td>
        <td><%= ts.created_at %></td>
        <td><%= ts.updated_at %></td>
        <td><%= ts.state %></td>
        <td><%= link_to 'Панель', cabinet_panel_path(id: ts.id), class: 'btn btn-default' %></td>

      </tr>
  </tbody>
  <% end %>
</table>

<h2>Full info: </h2>

<ul>
  <li>email: <%= @user.email %></li>
  <li>name: <%= @user.name %></li>
  <li>url: <%= @user.url %></li>
  <li>provider: <%= @user.provider %></li>
  <li>uid: <%= @user.uid %></li>
  <li>money: <%= @user.money %></li>
  <li>spent: <%= @user.spent %></li>
  <li>auto_extension: <%= @user.auto_extension %></li>
  <li>ref: <%= @user.ref %></li>
  <li>sign_in_count: <%= @user.sign_in_count %></li>
  <li>last_sign_in_ip: <%= @user.last_sign_in_ip %></li>
  <li>current_sign_in_ip: <%= @user.current_sign_in_ip %></li>
  <li>last_sign_in_at: <%= @user.last_sign_in_at %></li>
  <li>created_at: <%= @user.created_at %></li>

</ul>

app/views/admin/panel_tsserver.html.erb
<div class="update">
<%= form_for @ts, url: {controller: "admin", action: "update_panel_tsserver", id: @ts.id}, method: :post do |f|%>

  <% if @ts.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@ts.errors.count, "Ошибка") %></h2>

      <% @ts.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  <% end %>


  <div class="border">
    <%= f.label 'Server_id:' %>
    <%= f.number_field :server_id, value: @ts.server_id %>
  </div>



  <div class="border">
    <%= f.label 'user_id:' %>
    <%= f.number_field :user_id, value: @ts.user_id %>
  </div>


  <div class="border">
    <%= f.label 'machine_id:' %>
    <%= f.number_field :machine_id, value: @ts.machine_id %>
  </div>








  <%= f.submit "Update", class: 'btn btn-default'%>


<% end %>


</div>

app/views/admin/servers.html.erb
<h2>Server list in database</h2>

<table class="server-list">
  <thead>
  <tr>
    <th>ID</th>
    <th>IP</th>
    <th>Домен</th>
    <th>Кол-во слотов</th>
    <th>До какого оплачено</th>
    <th>Остаток дней</th>
    <th>user_id</th>
    <th>machine_id</th>
    <th>Дата создания</th>
    <th>Дата редактирования</th>
    <th>state</th>
  </tr>
  </thead>

  <% @ts.each do |ts| %>
      <tbody>
      <tr>
        <td><%= ts.id %></td>
        <td><%= Settings.other.ip[ts.server_id] + ':' + ts.port.to_s %></td>
        <td><%= ts.dns+'.'+ Settings.other.dns unless ts.dns.empty? %></td>
        <td><%= ts.slots %></td>
        <td><%= ts.time_payment %></td>
        <td><span id="left_time-<%=ts.id if ts.state %>">
            <script>
                var left_time = parseInt(<%= sec2days(ts.time_payment.to_time - Time.now).to_json %>);
                if(left_time > 7){
                    $('span#left_time-<%=ts.id %>').html('<h4>' + left_time + '</h4>').attr('style', 'color: green');
                }else if(left_time < 0){
                    $('span#left_time-<%=ts.id %>').html('<h4>' + left_time + '</h4>').attr('style', 'color: red');
                }else{
                    $('span#left_time-<%=ts.id %>').html('<h4>' + left_time + '</h4>').attr('style', 'color: yellow');
                };
            </script>
          </span></td>
        <td><%= ts.user_id %></td>
        <td><%= ts.machine_id %></td>
        <td><%= ts.created_at %></td>
        <td><%= ts.updated_at %></td>
        <td><%= ts.state %></td>
        <td><%= link_to 'Панель', cabinet_panel_path(ts), class: 'btn btn-default' %></td>
        <td><%= link_to 'Admin_Panel', admin_panel_tsserver_path(ts), class: 'btn btn-default' %></td>
      </tr>
      </tbody>
  <% end %>
</table>


<!--<h2>Server list physical</h2>-->





<!--<table class="server-list">-->
  <!--<thead>-->
  <!--<tr>-->
    <!--<th>machine_id</th>-->
    <!--<th>name</th>-->
    <!--<th>port</th>-->
    <!--<th>status</th>-->
    <!--<th>client_online</th>-->
    <!--<th>max_clients</th>-->
    <!--<th>auto_start</th>-->
  <!--</tr>-->
  <!--</thead>-->

  <!--<% @physical.each do |p| %>-->
      <!--<tbody>-->
      <!--<tr>-->
        <!--<td><%= p["virtualserver_id"] %></td>-->
        <!--<td><%= p["virtualserver_name"] %></td>-->
        <!--<td><%= p["virtualserver_port"] %></td>-->
        <!--<td><%= p["virtualserver_status"] %></td>-->
        <!--<td><%= p["virtualserver_clientsonline"] %></td>-->
        <!--<td><%= p["virtualserver_maxclients"] %></td>-->
        <!--<td><%= p["virtualserver_autostart"] %></td>-->
        <!--<td><%= link_to 'Delete', admin_del_physical_server_path(id: p["virtualserver_id"]), class: 'btn btn-default' %></td>-->
      <!--</tr>-->
      <!--</tbody>-->
  <!--<% end %>-->

<!--</table>-->

app/views/admin/user_list.html.erb
<h2>User list</h2>

<table class="server-list">
  <thead>
  <tr>
    <th>ID</th>
    <th>Email</th>
    <th>Money</th>
    <th>Всего потрачено</th>
    <th>Name</th>
    <th>Url</th>
  </tr>
  </thead>

  <% @users.each do |user| %>
      <tbody>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.money %></td>
        <td><%= user.spent %></td>
        <td><%= user.name %></td>
        <td><%= link_to(user.provider, user.url) if user.url %></td>
        <td><%= link_to 'Info', admin_info_path(id: user.id), class: 'btn btn-default' %></td>
      </tr>
      </tbody>
  <% end %>
</table>