config/routes.rb
Rails.application.routes.draw do


  class WalletoneMiddleware < Walletone::Middleware::Base
    def perform notify, env
      raise 'Wrong signature' unless notify.valid? Settings.w1.signature
        u = User.find(notify.WMI_DESCRIPTION.to_i)
        u.money = u.money+notify.WMI_PAYMENT_AMOUNT.to_i
        pay=Payment.new user_id: notify.WMI_DESCRIPTION.to_i, amount: notify.WMI_PAYMENT_AMOUNT.to_f, order_id: notify.fetch(:WMI_ORDER_ID)
        if pay.valid? and u.valid?
          pay.save!
          u.save!
          'Return some message for OK response'
        else
         raise 'Not saved'
        end
    end
  end

  # match '*path', via: :all, to: 'home#error_404'
  mount WalletoneMiddleware.new => '/w1_callback'

  # scope :unitpay do
  #   get :success, to: 'unitpay#success'
  #   get :fail, to: 'unitpay#fail'
  #   get :notify, to: 'unitpay#notify'
  # end

  post 'cabinet/edit_auto_extension', to: 'cabinet#edit_auto_extension', as: 'cabinet_edit_auto_extension'
  post 'cabinet/free_dns', to: 'cabinet#free_dns', as: 'cabinet_free_dns'
  get 'cabinet/pay', to: 'cabinet#pay', as: 'cabinet_pay'
  get 'cabinet/new', to: 'cabinet#new', as: 'cabinet_new'
  post 'cabinet/create', to: 'cabinet#create', as: 'cabinet_create'
  delete 'cabinet/:id', to: 'cabinet#destroy', as: 'cabinet_destroy'
  get 'cabinet', to: 'cabinet#home', as: 'cabinet_home'
  get 'cabinet/extend/:id', to: 'cabinet#extend', as: 'cabinet_extend'
  post 'cabinet/extend_up/:id', to: 'cabinet#extend_up'
  post 'cabinet/work/:id', to: 'cabinet#work', as: 'cabinet_work'
  get 'cabinet/edit/:id', to: 'cabinet#edit', as: 'cabinet_edit'
  post 'cabinet/update/:id', to: 'cabinet#update', as: 'cabinet_update'
  get 'cabinet/backups/:id', to: 'cabinet#backups', as: 'cabinet_backups'
  post 'cabinet/create_backup'
  post 'cabinet/delete_backup'
  post 'cabinet/apply_backup'
  get 'cabinet/token/:id', to: 'cabinet#token', as: 'cabinet_token'
  post 'cabinet/create_token', to: 'cabinet#create_token', as: 'cabinet_create_token'
  post 'cabinet/delete_token', to: 'cabinet#delete_token', as: 'cabinet_delete_token'
  post 'cabinet/reset_permissions/:id', to: 'cabinet#reset_permissions', as: 'cabinet_reset_permissions'
  get 'cabinet/settings/:id', to: 'cabinet#settings', as: 'cabinet_settings'
  post 'cabinet/settings_edit', to: 'cabinet#settings_edit', as: 'cabinet_settings_edit'
  # get 'cabinet/bans/:id', to: 'cabinet#bans', as: 'cabinet_bans'
  # post 'cabinet/ban', to: 'cabinet#ban', as: 'cabinet_ban'
  # post 'cabinet/unban', to: 'cabinet#unban', as: 'cabinet_unban'
  # post 'cabinet/unbanall', to: 'cabinet#unbanall', as: 'cabinet_unbanall'
  get 'cabinet/pay_redirect', to: 'cabinet#pay_redirect', as: 'cabinet_pay_redirect'
  get 'cabinet/ref', to: 'cabinet#ref', as: 'cabinet_ref'
  get 'cabinet/panel/:id', to: 'cabinet#panel', as: 'cabinet_panel'

  match '/ref/:ref' => 'home#ref', via: [:get, :post]
  get 'admin/info/:id', to: 'admin#info', as: 'admin_info'
  get 'admin/home'
  post 'admin/setmoney/:id', to: 'admin#setmoney'
  get 'admin/belongs_verification', to: 'admin#belongs_verification', as: 'admin_belongs_verification'
  get 'admin/user_list', to: 'admin#user_list', as: 'admin_user_list'
  get 'admin/servers', to: 'admin#servers', as: 'admin_servers'
  get 'admin/del_physical_server', to: 'admin#del_physical_server', as: 'admin_del_physical_server'
  get 'admin/amounts', to: 'admin#amounts', as: 'admin_amounts'
  post 'admin/destroy_payment', to: 'admin#destroy_payment', as: 'admin_destroy_payment'
  get 'admin/panel_tsserver/:id', to: 'admin#panel_tsserver', as: 'admin_panel_tsserver'
  post 'admin/update_panel_tsserver', to: 'admin#update_panel_tsserver', as: 'admin_update_panel_tsserver'


  root 'home#index'
  get '/home/regulations' => 'home#regulations', as: 'home_regulations'
  get 'home/index'
  get 'home/news'
  get '/home/how_buy' => 'home#how_buy', as: 'home_how_buy'

  devise_for :users, :controllers => {registrations: "registrations", passwords: "passwords", sessions: "sessions", omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:vk_callback]

  def index
  end

  def news
  end

  def ref
    cookies[:ref]={value: params[:ref], expires: 1.month.from_now,} if params[:ref] and params[:ref].to_i!=0 and current_user.blank?
    redirect_to root_path
  end

  def how_buy
  end

  def error_404
    render file: 'public/404.html', status: 404, layout: false
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/how_buy.html.erb
<div class="row">
  <div class="col-sm-6 col-md-6 col-lg-6">

  </div>
  <div class="col-sm-6 col-md-6 col-lg-6">

  </div>
</div>

app/views/home/index.html.erb
<style>
  .desc{
    text-align: center;
  }
</style>


<div class="main">
<!-- slider -->

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <div class="row">
          <div class="col-sm-2 col-md-2 col-lg-2"></div>
          <div class="col-sm-3 col-md-3 col-lg-3"><%= image_tag 'teamspeak.png', class: "center-block img-responsive", style: 'width: 150;' %></div>
          <div class="col-sm-5 col-md-5 col-lg-5" style="color: white; font-size: 20px; text-align: center;">
            <br>TeamSpeak - программа предназначенная для голосового общения между людьми, находящиеся на одном сервере, в одной комнате. Мы предлагаем вам сервер по цене <%= Settings.other.slot_cost %>р/слот в месяц, а также стабильную работу.
            <%= link_to 'Купить сервер', cabinet_new_path, class: 'btn btn-primary', style: 'margin-top: 10px; width: 200px;', data: { turbolinks: false } %>
          </div>
          <div class="col-sm-2 col-md-2 col-lg-2"></div>
        </div>
      </div>

      <div class="item">
          <div class="row">
            <div class="col-md-1 col-sm-1 col-lg-1"></div>
            <div class="col-md-5 col-sm-5 col-lg-5"><%= image_tag 'panel.jpg', class: "img-responsive", style: 'width:100%;'%></div>
            <div class="col-md-4 col-sm-4 col-lg-4" style="color: white; font-size: 20px; text-align: center;"><br>Функциональная панель управления с возможностью следить и управлять за своими серверами прямо с сайта. В будущем будет добавляться новый функционал, а также улучшаться старый. </div>
            <div class="col-md-2 col-sm-2 col-lg-2"></div>
          </div>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

<!-- slider end -->

<!-- description -->
  <div class="row center-block col-md-10 col-lg-11">

    <div class="col-sm-6 col-md-4 desc">
      <%= fa_stacked_icon "rocket inverse", base: "circle", class: "fa-3x" %>
      <div class="whyme">
        <h4>Быстрая скорость</h4>
        <p>Моментальная выдача сервера сразу после оплаты. Работоспособность серверов 24/7 </p>
      </div>
    </div>

    <div class="col-sm-6 col-md-4 desc">
      <%= fa_stacked_icon "cog inverse", base: "circle", class: "fa-3x" %>
      <div class="whyme">
        <h4>Простая панель управления</h4>
        <p>В личном кабинете вы с легкостью можете управлять сервером. </p>
      </div>
    </div>

    <div class="col-sm-6 col-md-4 desc">
      <%= fa_stacked_icon "rub  inverse", base: "circle", class: "fa-3x" %>
      <div class="whyme">
        <h4>Низкие Цены</h4>
        <p>У нас низкие цены на аренду сервера TeamSpeak 3, <%= Settings.other.slot_cost %>руб/слот.</p>
      </div>
    </div>

    <div class="col-sm-6 col-md-4 desc">
      <%= fa_stacked_icon "handshake-o inverse", base: "circle", class: "fa-3x" %>
      <div class="whyme">
        <h4>Сотрудничество</h4>
        <p>Наше сотрудничество предлагает спонсирования ваших проектов на определенных условиях. Обращаться в официальную группу Вконтакте.  </p>
      </div>
    </div>

    <div class="col-sm-6 col-md-4 desc">
      <%= fa_stacked_icon "money inverse", base: "circle", class: "fa-3x" %>
      <div class="whyme">
        <h4>Партнерская программа</h4>
        <p>Наша партнерская программа поможет Вам заработать средства для оплаты сервера. Приглашайте новых пользователей и получайте 10% от каждого заказа Вашего реферала.</p>
      </div>
    </div>

    <div class="col-sm-6 col-md-4 desc">
      <%= fa_stacked_icon "refresh inverse", base: "circle", class: "fa-3x" %>
      <div class="whyme">
        <h4>Снимки сервера </h4>
        <p>Простое создание бэкапов сервера - Вы можете откатить изменения на Вашем сервере из личного кабинета.</p>
      </div>
    </div>

  </div>




</div>

<div class="text-center"">


</div>

app/views/home/news.html.erb
  <script type="text/javascript" src="//vk.com/js/api/openapi.js?144"></script>

  <!-- VK Widget -->
  <div id="vk_groups"></div>
  <script type="text/javascript">
      VK.Widgets.Group("vk_groups", {mode: 4, wide: 1, width: "auto", height: "800"}, 126399695);
  </script>

app/views/home/regulations.html.erb
<style>

  ol{
    list-style: none;
    counter-reset: li;
  }

  div ol
  li:before {
    counter-increment: li;
    content: counters(li, ".") ". ";
  }

  .fat{
    font-weight: 600;
  }
</style>

<div>
  <h2 class="text-center">Пользовательское соглашение</h2>
  <ol>
    <li><span class="fat">ОБЩИЕ ПОЛОЖЕНИЯ</span>
      <ol>
        <li>Настоящее Соглашение регулирует отношения между Администрацией сайта Интернет-магазина « easy-ts.ru  » – Администрация сайта и Пользователем данного Сайта.</li>
        <li>Администрация сайта оставляет за собой право в любое время изменять, добавлять или удалять пункты настоящего Соглашения без уведомления Пользователя.</li>
        <li>Продолжение использования Сайта Пользователем означает принятие Соглашения и изменений, внесенных в настоящее Соглашение.</li>
        <li>Пользователь несет персональную ответственность за проверку настоящего Соглашения на наличие изменений в нем.</li>
      </ol>
    </li>
    <br>
    <li><span class="fat">ПРЕДМЕТ СОГЛАШЕНИЯ</span>
      <ol>
        <li>Настоящее Соглашение является публичной офертой. Получая доступ к Сайту Пользователь считается присоединившимся к настоящему Соглашению.</li>
      </ol>
    </li>
    <br>
    <li><span class="fat">ПРАВА И ОБЯЗАННОСТИ СТОРОН</span>
      <ol>
        <li>Изменять правила пользования Сайтом, а также изменять содержание данного Сайта. Изменения вступают в силу с момента публикации новой редакции Соглашения на Сайте.</li>
        <li>Ограничить доступ к Сайту в случае нарушения Пользователем условий настоящего Соглашения.</li>
        <li>Изменять размер оплаты, взимаемый за предоставление доступа к использованию сайта Интернет-магазина. Изменение стоимости будет распространяться на Пользователей, имеющих регистрацию к моменту изменения размера оплаты, за исключением случаев, особо оговоренных Администрацией сайта интернет-магазина.</li>
        <li>Получить доступ к использованию Сайта после соблюдения требований о регистрации и оплате.</li>
        <li>Соблюдать имущественные и неимущественные права авторов и иных правообладателей при использовании Сайта.</li>
      </ol>
    </li>
    <br>
    <li><span class="fat">Пользователь Сайта обязуется:</span>
      <ol>
        <li>Предоставлять по запросу Администрации сайта дополнительную информацию, которая имеет непосредственное отношение к предоставляемым услугам данного Сайта.</li>
        <li>Соблюдать имущественные и неимущественные права авторов и иных правообладателей при использовании Сайта.</li>
        <li>Не предпринимать действий, которые могут рассматриваться как нарушающие нормальную работу Сайта.</li>
        <li>Не распространять с использованием Сайта любую конфиденциальную и охраняемую законодательством Российской Федерации информацию о физических либо юридических лицах.</li>
        <li>Не использовать Сайт для распространения информации рекламного характера, иначе как с согласия Администрации сайта.</li>
        <li><span class="fat">Не использовать сервисы сайта Интернет-магазина с целью:</span>
          <ol>
            <li>загрузки контента, который является незаконным, нарушает любые права третьих лиц; пропагандирует насилие, жестокость, ненависть и (или) дискриминацию по расовому, национальному, половому, религиозному, социальному признакам; содержит недостоверные сведения и (или) оскорбления в адрес конкретных лиц, организаций, органов власти.</li>
            <li>побуждения к совершению противоправных действий, а также содействия лицам, действия которых направлены на нарушение ограничений и запретов, действующих на территории Российской Федерации.</li>
            <li>ущемления прав меньшинств</li>
            <li>представления себя за другого человека или представителя организации и (или) сообщества без достаточных на то прав, в том числе за сотрудников данного Интернет-магазина.</li>
            <li>некорректного сравнения Товара, а также формирования негативного отношения к лицам, (не) пользующимся определенными Товарами, или осуждения таких лиц.</li>
          </ol>
        </li>
      </ol>
    </li>
    <br>
    <li><span class="fat">Пользователю запрещается:</span>
      <ol>
        <li>Использовать любые устройства, программы, процедуры, алгоритмы и методы, автоматические
          устройства или
          эквивалентные ручные процессы для доступа, приобретения, копирования или отслеживания содержания Сайта данного Интернет-магазина;</li>
        <li>Нарушать надлежащее функционирование Сайта;</li>
        <li>Любым способом обходить навигационную структуру Сайта для получения или попытки получения любой информации, документов или материалов любыми средствами, которые специально не представлены сервисами данного Сайта;</li>
        <li>Нарушать систему безопасности или аутентификации на Сайте или в любой сети, относящейся к Сайту.</li>
        <li>Выполнять обратный поиск, отслеживать или пытаться отслеживать любую информацию о любом другом Пользователе Сайта.</li>
        <li>Использовать Сайт и его Содержание в любых целях, запрещенных законодательством Российской Федерации, а также подстрекать к любой незаконной деятельности или другой деятельности, нарушающей права интернет-магазина или других лиц.</li>
        <li>Администрация сайта обладает правом в одностороннем порядке аннулировать учетную запись Пользователя, если она не использовалась более 6 месяцев календарных месяцев подряд без уведомления Пользователя.</li>
        <li>Администрация сайта имеет право в любое время без уведомления Пользователя вносить изменения в перечень Товаров и услуг, предлагаемых на Сайте, и (или) в цены, применимые к таким Товарам по их реализации и (или) оказываемым услугам Интернет-магазином.</li>
      </ol>
    </li>
    <br>
    <li><span class="fat">ОТВЕТСТВЕННОСТЬ</span>
      <ol>
        <li>Любые убытки, которые Пользователь может понести в случае умышленного или неосторожного нарушения любого положения настоящего Соглашения, а также вследствие несанкционированного доступа к коммуникациям другого Пользователя, Администрацией сайта не возмещаются.</li>
        <li>Администрация сайта не несет ответственности за:
          <ol>
            <li>Задержки или сбои в процессе совершения операции, возникшие вследствие непреодолимой силы, а также любого случая неполадок в телекоммуникационных, компьютерных, электрических и иных смежных системах.</li>
            <li>Действия систем переводов, банков, платежных систем и за задержки связанные с их работой.</li>
            <li>Надлежащее функционирование Сайта, в случае, если Пользователь не имеет необходимых технических средств для его использования, а также не несет никаких обязательств по обеспечению пользователей такими средствами.</li>
          </ol>
        </li>

      </ol>
    </li>
    <br>
    <li><span class="fat">НАРУШЕНИЕ УСЛОВИЙ ПОЛЬЗОВАТЕЛЬСКОГО СОГЛАШЕНИЯ</span>
      <ol>
        <li>Администрация сайта вправе раскрыть любую собранную о Пользователе данного Сайта информацию, если раскрытие необходимо в связи с расследованием или жалобой в отношении неправомерного использования Сайта либо для установления (идентификации) Пользователя, который может нарушать или вмешиваться в права Администрации сайта или в права других Пользователей Сайта.</li>
        <li>Администрация сайта имеет право раскрыть любую информацию о Пользователе, которую посчитает необходимой для выполнения положений действующего законодательства или судебных решений, обеспечения выполнения условий настоящего Соглашения, защиты прав или безопасности название организации, Пользователей.</li>
        <li>Администрация сайта имеет право раскрыть информацию о Пользователе, если действующее законодательство Российской Федерации требует или разрешает такое раскрытие.</li>
        <li>Администрация сайта вправе без предварительного уведомления Пользователя прекратить и (или) заблокировать доступ к Сайту, если Пользователь нарушил настоящее Соглашение или содержащиеся в иных документах условия пользования Сайтом, а также в случае прекращения действия Сайта либо по причине технической неполадки или проблемы.</li>
        <li>Администрация сайта не несет ответственности перед Пользователем или третьими лицами за прекращение доступа к Сайту в случае нарушения Пользователем любого положения настоящего Соглашения или иного документа, содержащего условия пользования Сайтом.</li>
      </ol>
    </li>
    <br>
    <li><span class="fat">РАЗРЕШЕНИЕ СПОРОВ</span>
      <ol>
        <li>В случае
          возникновения любых
          разногласий или споров между Сторонами настоящего Соглашения обязательным условием до обращения в суд является предъявление претензии (письменного предложения о добровольном урегулировании спора).</li>
        <li>Получатель претензии в течение 30 календарных дней со дня ее получения, письменно уведомляет заявителя претензии о результатах рассмотрения претензии.</li>
        <li>При невозможности разрешить спор в добровольном порядке любая из Сторон вправе обратиться в суд за защитой своих прав, которые предоставлены им действующим законодательством Российской Федерации.</li>
        <li>Любой иск в отношении условий использования Сайта должен быть предъявлен в течение срок после возникновения оснований для иска, за исключением защиты авторских прав на охраняемые в соответствии с законодательством материалы Сайта. При нарушении условий данного пункта любой иск или основания для иска погашаются исковой давностью.</li>
      </ol>
    </li>
    <br>
    <li><span class="fat">ДОПОЛНИТЕЛЬНЫЕ УСЛОВИЯ</span>
      <ol>
        <li>Администрация сайта не принимает встречные предложения от Пользователя относительно изменений настоящего Пользовательского соглашения.</li>
        <li>Отзывы Пользователя, размещенные на Сайте, не являются конфиденциальной информацией и могут быть использованы Администрацией сайта без ограничений.</li>
      </ol>
    </li>

  </ol>
  <br>

  <p>Обновлено 29 апреля 2017 г.</p>
</div>