config/routes.rb
Rails.application.routes.draw do


  class WalletoneMiddleware < Walletone::Middleware::Base
    def perform notify, env
      raise 'Wrong signature' unless notify.valid? Settings.w1.signature
        u = User.find(notify.WMI_DESCRIPTION.to_i)
        u.money = u.money+notify.WMI_PAYMENT_AMOUNT.to_i
        pay=Payment.new user_id: notify.WMI_DESCRIPTION.to_i, amount: notify.WMI_PAYMENT_AMOUNT.to_f, order_id: notify.fetch(:WMI_ORDER_ID)
        if pay.valid? and u.valid?
          pay.save!
          u.save!
          'Return some message for OK response'
        else
         raise 'Not saved'
        end
    end
  end

  # match '*path', via: :all, to: 'home#error_404'
  mount WalletoneMiddleware.new => '/w1_callback'

  # scope :unitpay do
  #   get :success, to: 'unitpay#success'
  #   get :fail, to: 'unitpay#fail'
  #   get :notify, to: 'unitpay#notify'
  # end

  post 'cabinet/edit_auto_extension', to: 'cabinet#edit_auto_extension', as: 'cabinet_edit_auto_extension'
  post 'cabinet/free_dns', to: 'cabinet#free_dns', as: 'cabinet_free_dns'
  get 'cabinet/pay', to: 'cabinet#pay', as: 'cabinet_pay'
  get 'cabinet/new', to: 'cabinet#new', as: 'cabinet_new'
  post 'cabinet/create', to: 'cabinet#create', as: 'cabinet_create'
  delete 'cabinet/:id', to: 'cabinet#destroy', as: 'cabinet_destroy'
  get 'cabinet', to: 'cabinet#home', as: 'cabinet_home'
  get 'cabinet/extend/:id', to: 'cabinet#extend', as: 'cabinet_extend'
  post 'cabinet/extend_up/:id', to: 'cabinet#extend_up'
  post 'cabinet/work/:id', to: 'cabinet#work', as: 'cabinet_work'
  get 'cabinet/edit/:id', to: 'cabinet#edit', as: 'cabinet_edit'
  post 'cabinet/update/:id', to: 'cabinet#update', as: 'cabinet_update'
  get 'cabinet/backups/:id', to: 'cabinet#backups', as: 'cabinet_backups'
  post 'cabinet/create_backup'
  post 'cabinet/delete_backup'
  post 'cabinet/apply_backup'
  get 'cabinet/token/:id', to: 'cabinet#token', as: 'cabinet_token'
  post 'cabinet/create_token', to: 'cabinet#create_token', as: 'cabinet_create_token'
  post 'cabinet/delete_token', to: 'cabinet#delete_token', as: 'cabinet_delete_token'
  post 'cabinet/reset_permissions/:id', to: 'cabinet#reset_permissions', as: 'cabinet_reset_permissions'
  get 'cabinet/settings/:id', to: 'cabinet#settings', as: 'cabinet_settings'
  post 'cabinet/settings_edit', to: 'cabinet#settings_edit', as: 'cabinet_settings_edit'
  # get 'cabinet/bans/:id', to: 'cabinet#bans', as: 'cabinet_bans'
  # post 'cabinet/ban', to: 'cabinet#ban', as: 'cabinet_ban'
  # post 'cabinet/unban', to: 'cabinet#unban', as: 'cabinet_unban'
  # post 'cabinet/unbanall', to: 'cabinet#unbanall', as: 'cabinet_unbanall'
  get 'cabinet/pay_redirect', to: 'cabinet#pay_redirect', as: 'cabinet_pay_redirect'
  get 'cabinet/ref', to: 'cabinet#ref', as: 'cabinet_ref'
  get 'cabinet/panel/:id', to: 'cabinet#panel', as: 'cabinet_panel'

  match '/ref/:ref' => 'home#ref', via: [:get, :post]
  get 'admin/info/:id', to: 'admin#info', as: 'admin_info'
  get 'admin/home'
  post 'admin/setmoney/:id', to: 'admin#setmoney'
  get 'admin/belongs_verification', to: 'admin#belongs_verification', as: 'admin_belongs_verification'
  get 'admin/user_list', to: 'admin#user_list', as: 'admin_user_list'
  get 'admin/servers', to: 'admin#servers', as: 'admin_servers'
  get 'admin/del_physical_server', to: 'admin#del_physical_server', as: 'admin_del_physical_server'
  get 'admin/amounts', to: 'admin#amounts', as: 'admin_amounts'
  post 'admin/destroy_payment', to: 'admin#destroy_payment', as: 'admin_destroy_payment'
  get 'admin/panel_tsserver/:id', to: 'admin#panel_tsserver', as: 'admin_panel_tsserver'
  post 'admin/update_panel_tsserver', to: 'admin#update_panel_tsserver', as: 'admin_update_panel_tsserver'


  root 'home#index'
  get '/home/regulations' => 'home#regulations', as: 'home_regulations'
  get 'home/index'
  get 'home/news'
  get '/home/how_buy' => 'home#how_buy', as: 'home_how_buy'

  devise_for :users, :controllers => {registrations: "registrations", passwords: "passwords", sessions: "sessions", omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cabinet_controller.rb
class CabinetController < ApplicationController
helper CabinetHelper
require 'date'
require 'base64'
	before_action :authenticate_user!
	before_action :ts_params, only: [:create]
  before_action :own_server, only: [:panel, :settings_edit, :settings, :reset_permissions, :apply_backup,
                                    :delete_backup, :create_backup, :backups, :delete_token, :create_token,
                                    :token, :work, :extend_up, :extend, :destroy, :update, :edit]
  rescue_from Teamspeak::ServerError, :with => :invalid_server
  
def home
    @servers = Tsserver.where(user_id: current_user.id).select(:machine_id,:server_id)
    return if @servers.blank?
    servs = Array.new
    @servers.each { |temp| servs << temp.machine_id }
    server = Teamspeak::Functions.new(@servers.first.server_id) #TODO: сделать чтобы если у пользователя сервера на разных машинах server_list брать с разных машин и получать статус
    @status = server_status(server.server_list, servs)
    server.disconnect
end

def edit
  @days = Teamspeak::Other.sec2days(@ts.time_payment.to_time - Time.now)
end

def update
  unless params[:tsserver][:dns]==@ts.dns and params[:tsserver][:slots]==@ts.slots
      days = Teamspeak::Other.sec2days(@ts.time_payment.to_time - Time.now)
      old_dns = @ts.dns
      cost = (((params[:tsserver][:slots].to_i - @ts.slots) * (Settings.other.slot_cost.to_f/30*days))).round 2
      cost += 10 if old_dns != params[:tsserver][:dns]
      if current_user.have_money?(cost)
        if @ts.valid?
          if @ts.update dns: params[:tsserver][:dns], slots: params[:tsserver][:slots]
            server = Teamspeak::Functions.new(@ts.server_id)
            current_user.update! money: ((current_user.money - cost).round 2), spent: current_user.spent+=cost
            referall_system cost, current_user.ref
            server.server_edit_slots @ts.machine_id, params[:tsserver][:slots]
            if !old_dns.empty? and !params[:tsserver][:dns].empty?
              Teamspeak::Other.edit_dns(old_dns, @ts.port,params[:tsserver][:dns],@ts.port,@ts.server_id)
            elsif !old_dns.empty? and params[:tsserver][:dns].empty?
              Teamspeak::Other.del_dns(old_dns, @ts.port, @ts.server_id)
            elsif old_dns.empty? and !params[:tsserver][:dns].empty?
              Teamspeak::Other.new_dns(params[:tsserver][:dns],@ts.port,@ts.server_id)
            end
            redirect_to cabinet_panel_path(params[:id]), success: 'Вы успешно редактировали сервер'
            server.disconnect
          else
            render 'cabinet/edit'
          end
        end
      else
        redirect_to cabinet_home_path, danger: 'Недостаточно средст'
      end

  else
    redirect_to cabinet_home_path, info: 'Вы ничего не изменили'
  end
end


def new
  @ts=Tsserver.new
end


def create
    server=Teamspeak::Functions.new(0) #TODO: сделать выбор сервера
    @ts = Tsserver.new(ts_params)
    time = ts_params[:time_payment].to_i
    if [1,2,3,6,12].include?(time)
      @ts.time_payment, @ts.user_id, cost = time, current_user.id, time * Settings.other.slot_cost.to_i * @ts.slots
        if current_user.have_money?(cost)
          if @ts.valid?
            @ts.time_payment = Date.today + 30*time
            data=server.server_create(free_port,@ts.slots)
            @ts.machine_id, @ts.port, @token = data['sid'], data['virtualserver_port'], data['token']
              if @ts.save and current_user.update(money: ((current_user.money - cost).round(2)), spent: current_user.spent+cost)
                referall_system cost, current_user.ref
                Teamspeak::Other.new_dns(@ts.dns, @ts.port, @ts.server_id) unless @ts.dns.blank?
                redirect_to cabinet_home_path, success:'Вы успешно создали сервер', info:"Ваш ключ: #{@token}"
              else
                server.server_destroy @ts.machine_id
                Teamspeak::Other.del_dns(@ts.dns, @ts.port,@ts.server_id) unless @ts.dns.blank?
                redirect_to cabinet_new_path(@ts), danger: 'Что-то пошло не так, отпишите администрации чтобы они это починили.'
              end

          else
             render cabinet_new_path @ts
          end
        else
          redirect_to cabinet_home_path, danger:'Недостаточно средств'
        end
    else
      render 'new'
    end
  server.disconnect
end



def destroy
        server=Teamspeak::Functions.new(@ts.server_id)
        dns, port = @ts.dns, @ts.port
        server.server_destroy(@ts.machine_id)
        Teamspeak::Other.del_dns(dns, port,@ts.server_id) unless dns.empty?
        b = Backup.where tsserver_id: @ts.id
        b.destroy_all
        if @ts.destroy
          redirect_to cabinet_home_path, success: 'Вы успешно удалили сервер'
        end
        server.disconnect

end

def extend

end

def extend_up
  user = current_user
  time = params[:tsserver][:time_payment].to_i
  cab = Teamspeak::Functions.new(@ts.server_id)
  cost = @ts.slots * Settings.other.slot_cost.to_i * time
  if [1,2,3,6,12].include?(time)
    if user.have_money?(cost)
        user.spent+= cost
        user.money = user.money - cost
        @ts.state = true
        if Date.today <= @ts.time_payment
          @ts.time_payment = @ts.time_payment + time * 30
        else
          @ts.time_payment = Date.today + time * 30
          #cab.server_start(@ts.machine_id)
          cab.server_autostart @ts.machine_id, 1
        end
        if @ts.save validate:false and user.save
          referall_system cost, current_user.ref
          redirect_to cabinet_home_path, success:'Вы успешно продлил'
        end
        cab.disconnect

    else
      redirect_to cabinet_home_path, danger: 'Недостаточно средств'
    end
  else
    redirect_to cabinet_home_path
  end
end

def work
        if @ts.state
          server=Teamspeak::Functions.new(@ts.server_id)
          if server.server_status(@ts.machine_id)
            server.server_stop @ts.machine_id
            redirect_to cabinet_panel_path, success: 'Вы успешно выключили сервер'
          else
            server.server_start @ts.machine_id
            redirect_to cabinet_panel_path, success: 'Вы успешно включили сервер'
          end
          server.disconnect
        else
          redirect_to cabinet_home_path, warning: 'Продлите сервер'
        end
end


def token
      server = Teamspeak::Functions.new(@ts.server_id)
      @tokens = server.token_list(@ts.machine_id)
      @groups = {}
      server.group_list(@ts.machine_id).each {|t| @groups.merge!({"#{t['name'].force_encoding("UTF-8")}":t['sgid']}) if t["type"]==1}
      server.disconnect
end

def create_token
    server = Teamspeak::Functions.new(@ts.server_id)
    server.create_token(@ts.machine_id, params[:group_id], params[:description])
    redirect_to cabinet_token_path(params[:id]), success: 'Вы успешно создали токен'
    server.disconnect
end

def delete_token
    server = Teamspeak::Functions.new(@ts.server_id)
    server.delete_token @ts.machine_id, params[:token]
    redirect_to cabinet_token_path params[:id]
    server.disconnect
end

def pay

end

def pay_redirect
  if params[:money].to_i >= 10
    payment = Walletone::Payment.new(
        WMI_MERCHANT_ID:    Settings.w1.merchant_id,
        WMI_PAYMENT_AMOUNT:  params[:money], # Сумма
        WMI_CURRENCY_ID:     643, # ISO номер валюты (По умолчанию 643 - Рубль),
        WMI_DESCRIPTION: current_user.id.to_s,
        WMI_SUCCESS_URL: 'https://easy-ts.ru/cabinet',
        WMI_FAIL_URL: 'https://easy-ts.ru/cabinet'
    )
    payment.sign! Settings.w1.signature

    @form = payment.form
  else
    redirect_to cabinet_pay_path, warning: 'Сумма должна быть больше или равна 5 рублей'
  end
end

def pay_unitpay
  redirect_to ''
end

def free_dns
  dns_list = Tsserver.pluck(:dns)
  status = dns_list.include?(params[:dns]) ? true:false
  respond_to do |format|
    format.json { render :json => {status: status} }
  end
end

def edit_auto_extension
  unless current_user.auto_extension == params[:auto_extension]
    current_user.update auto_extension: params[:auto_extension]
  end
end

def backups
    @backups = Backup.where(tsserver_id: params[:id])
end

def create_backup
  unless backup = Backup.where(tsserver_id: params[:id]).count >= 3
    server = Teamspeak::Functions.new(@ts.server_id)
    backup = Backup.new(tsserver_id: params[:id], data: server.create_backup(@ts.machine_id).to_s)
    server.disconnect
    if backup.save
      redirect_to cabinet_backups_path(params[:id]), success: 'Вы успешно создали бекап!'
    else
      redirect_to cabinet_backups_path(params[:id]), danger: 'Что-то пошло не так'
    end

  else
    redirect_to cabinet_backups_path(params[:id]), warning: 'Вы превысили лимит бекапов'
  end
end

def delete_backup
    backup = Backup.find params[:backup_id]
    backup.destroy ? (redirect_to cabinet_backups_path(backup.tsserver_id), success: 'Вы успешно удалили!' ):(redirect_to cabinet_backups_path(backup.tsserver_id), danger: 'Что-то пошло не так')
end

def apply_backup
    backup = Backup.find params[:backup_id]
    server = Teamspeak::Functions.new(@ts.server_id)
    server.deploy_backup(@ts.machine_id, backup.data)
    redirect_to cabinet_backups_path(backup.tsserver_id), success: 'Вы успешно применили бекап!'
    server.disconnect
end

def reset_permissions
    server = Teamspeak::Functions.new(@ts.server_id)
    server.reset_permissions @ts.machine_id
    redirect_to cabinet_home_path, success: 'Вы успешно сбросили права'
    server.disconnect
end

def settings
    server = Teamspeak::Functions.new(@ts.server_id)
    info = server.server_info @ts.machine_id
    @name, @welcome_message = info['virtualserver_name'].force_encoding(Encoding::UTF_8), info['virtualserver_welcomemessage'].force_encoding(Encoding::UTF_8)
    server.disconnect
end

def settings_edit
    server = Teamspeak::Functions.new(@ts.server_id)
    server.set_settings @ts.machine_id, params[:name], params[:welcome_message], params[:pass]

app/helpers/cabinet_helper.rb
module CabinetHelper

	def sec2days(sec)
		time = sec.round
		time /= 60
		time /= 60
		time /= 24
		time+=2
	end
	
	
	def panel_gen
		content = ''
		content += image_tag 'teamspeak/16x16_server_green.png'
		content += @info['virtualserver_name']
		content += renderChannels 0
	end
	
	
	def renderChannels channelID
		content = ''
		@channel.each do |channel|
			if channel['pid'] == channelID
				name = channel['channel_name'].to_s
				icon = '16x16_channel_green.png'
				if channel['channel_maxclients'] > -1 and channel['total_clients'] >= channel['channel_maxclients']
					icon = '16x16_channel_red.png'
				elsif channel['channel_maxfamilyclients'] > -1 and channel['total_clients_family'] >= channel['channel_maxfamilyclients']
					icon = '16x16_channel_red.png'
				elsif channel['channel_flag_password'] == 1
					icon = '16x16_channel_yellow.png'
				end
				
				flags = Array.new
				flags << '16x16_default.png' if channel['channel_flag_default'] == 1
				flags << '16x16_moderated.png' if channel['channel_needed_talk_power'] > 0
				flags << '16x16_register.png' if channel['channel_flag_password'] == 1
				flags = renderFlags flags
				
				users = renderUsers channel['cid'] unless @client.blank?
				childs = renderChannels(channel['cid'])
				cid = channel['cid']
				
				
				
				content += "<div class='tsstatusItem'>"
				content += image_tag "teamspeak/#{icon}"
				content += name
				content += "<div class='tsstatusFlags'>"
				content += flags
				content += "</div> #{users} #{childs} </div>"
			end
		end
		return content
	end
	
	def renderFlags flags
		content = ''
		flags.each do |flag|
			content += image_tag "teamspeak/#{flag}"
		end
		return content
	end
	
	def renderUsers channelID
		content=''
		
		@client.each do |user|
			if user['cid']==channelID
				if user['client_type'] == 0
					@count_users+=1
					name = user['client_nickname'].to_s
					icon = '16x16_player_off.png'
					if(user['client_away'] == 1) then icon = '16x16_away.png'
					elsif(user['client_flag_talking'] == 1) then icon = '16x16_player_on.png'
					elsif(user['client_output_hardware'] == 0) then icon = '16x16_hardware_output_muted.png'
					elsif(user['client_output_muted'] == 1) then icon = '16x16_output_muted.png'
					elsif(user['client_input_hardware'] == 0) then icon = '16x16_hardware_input_muted.png'
					elsif(user['client_input_muted'] == 1) then icon = '16x16_input_muted.png'
					end
					
					
					content += "<div class='tsstatusItem'>"
					content += image_tag "teamspeak/#{icon}"
					content += name
					content += "</div>"
				end
			
			end
		end
		return content
	end





end

app/views/cabinet/backups.html.erb
<h1>Список бекапов</h1>




    <table class="table">
      <thead>
      <tr>
        <th>Дата создания</th>

      </tr>
      </thead>

      <tbody>
      <% @backups.each do |b| %>
          <tr>
              <td><%= b.created_at %></td>
              <td><%= link_to 'Применить', cabinet_apply_backup_path(backup_id: b.id, id: @ts.id), method: :post, class: "btn btn-success"  %></td>
              <td><%= link_to 'Удалить', cabinet_delete_backup_path(backup_id: b.id, id: @ts.id), method: :post, class: "btn btn-danger"  %></td>


          </tr>
      <% end %>
      </tbody>
    </table>

    <td><%= link_to 'Создать', cabinet_create_backup_path(id: @ts.id), method: :post, class: "btn btn-primary"  %></td>

<br>
<%= link_to 'Назад', cabinet_panel_path(@ts.id), class: "btn btn-default" %>

app/views/cabinet/bans.html.erb
<h2>Список банов</h2>

<%= form_tag cabinet_ban_path, method: :post do %>

    <table><tr>
      <td><%= select_tag :param, options_for_select(Tsserver::Ban_Data), class: 'select_group' %></td>
      <td><%= text_field_tag :name%></td>
      <td><%= text_field_tag :reasons%></td>
      <td><%= number_field_tag :duration, 0%></td>
      <td><%= hidden_field_tag :id,params[:id] %></td>
      <td><%= submit_tag 'Забанить' %></td>
    </tr></table>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th>IP</th>
    <th>Никнейм</th>
    <th>uid</th>
    <th>Причина</th>
    <th>До</th>

  </tr>
  </thead>
  <% @bans.each do |b|%>
      <tbody><% break if b['banid'].blank? %>
      <tr>
        <td><%= b["ip"] %></td>
        <td><%= b["name"] %></td>
        <td><%= b["uid"] %></td>
        <td><%= b["reason"] %></td>
        <td><%= b["duration"].to_i==0 ? 'permanent':(Time.now + b["duration"].to_i) %></td>

        <td><%= link_to 'Разбанить', cabinet_unban_path(banid: b['banid'],id: params[:id]), method: :post %></td>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/cabinet/home.html.erb
<div>
На вашем счету: <%= current_user.money %> руб.<%= link_to 'Пополнить', cabinet_pay_path, class: 'btn btn-default' %>
<%= link_to 'Купить сервер', cabinet_new_path, class: 'btn btn-default', data: { turbolinks: false } %>
<%= link_to 'Реферальная программа', cabinet_ref_path, class: 'btn btn-default' %>
</div>
<h4>Авто-продление</h4>
<div class="btn-group" id="toggle_event_editing">
  <button type="button" class="btn btn-info locked_active">OFF</button>
  <button type="button" class="btn btn-default unlocked_inactive">ON</button>
</div>

<h2>Список серверов</h2>
<div>
  <table class="table">
    <thead>
      <tr>
        <th>Доменное имя</th>
        <th>IP</th>
        <th>Количество слотов</th>
        <th>Дата следующего платежа</th>
        <th>Остаток дней</th>
        <th>Статус</th>

      </tr>
    </thead>

    <tbody>
      <% current_user.tsservers.each do |ts| %>
        <tr>
          <td><%= ts.dns+'.'+Settings.other.dns unless ts.dns == '' %></td>
          <td><%= Settings.other.ip[ts.server_id] + ':' + ts.port.to_s %></td>
          <td><%= ts.slots %></td>
          <td><%= ts.time_payment %></td>
          <td><span id="left_time-<%=ts.id %>">
            <script>
                var left_time = parseInt(<%= sec2days(ts.time_payment.to_time - Time.now).to_json %>);
                  if(left_time > 7){
                      $('span#left_time-<%=ts.id %>').html('<h4>' + left_time + '</h4>').attr('style', 'color: green');
                  }else if(left_time < 0){
                      $('span#left_time-<%=ts.id %>').html('<h4>' + left_time + '</h4>').attr('style', 'color: red');
                  }else{
                      $('span#left_time-<%=ts.id %>').html('<h4>' + left_time + '</h4>').attr('style', 'color: yellow');
                  };
            </script>
          </span></td>
          <td><%= (@status[@status.index(ts.machine_id).to_i+1]=='online') ? 'Online':'Offline' unless @status.blank? %></td>


          <td><%= link_to 'Панель', cabinet_panel_path(ts), class: 'btn btn-default' %></td>


        </tr>
      <% end %>
    </tbody>
  </table>
</div>




<script type="text/javascript" charset="utf-8">

    if((<%= current_user.auto_extension %>) && (($('#toggle_event_editing button').hasClass('locked_active')) || (('#toggle_event_editing button').hasClass('locked_active')))){
        $('#toggle_event_editing button').eq(0).toggleClass('locked_inactive locked_active btn-default btn-info');
        $('#toggle_event_editing button').eq(1).toggleClass('unlocked_inactive unlocked_active btn-info btn-default');
    }


    $('#toggle_event_editing button').click(function(){
        if($(this).hasClass('locked_active') || $(this).hasClass('unlocked_inactive')){
            $.ajax({
                type: 'POST',
                url: "/cabinet/edit_auto_extension",
                data: {auto_extension: true}
            });
            $('#toggle_event_editing button').eq(0).toggleClass('locked_inactive locked_active btn-default btn-info');
            $('#toggle_event_editing button').eq(1).toggleClass('unlocked_inactive unlocked_active btn-info btn-default');
        }else{
          /* code to do when locking */
            $.ajax({
                type: 'POST',
                url: "/cabinet/edit_auto_extension",
                data: {auto_extension: false}
            });
            $('#toggle_event_editing button').eq(0).toggleClass('locked_inactive locked_active btn-default btn-info');
            $('#toggle_event_editing button').eq(1).toggleClass('unlocked_inactive unlocked_active btn-info btn-default');
        }})

</script>

app/views/cabinet/panel.html.erb
<style>
  a.btn{
    width: 200px;
  }
</style>

<div class="row">
  <div class="col-md-6">

<div class="functions">
  <ul style="list-style-type: none">
    <li><%= link_to 'Токены', cabinet_token_path(@ts), class: 'btn btn-primary'%></li>
    <li><%= link_to 'Настройки', cabinet_settings_path(@ts), class: 'btn btn-primary' %></li>
    <li><%= link_to 'Редактировать', cabinet_edit_path(@ts), data: { turbolinks: false }, class: 'btn btn-primary'%></li>
    <li><%= link_to 'Бекапы', cabinet_backups_path(@ts), class: 'btn btn-primary' %></li>
    <li><%= link_to 'Вкл/Выкл', cabinet_work_path(@ts), method: :post, class: 'btn btn-primary' %></li>
    <li><%= link_to 'Продлить', cabinet_extend_path(@ts), class: 'btn btn-primary'%></li>
    <li><%= link_to 'Сбросить права', cabinet_reset_permissions_path(@ts), data: {confirm: 'Вы уверены?'}, method: :post, class: 'btn btn-danger'%></li>
    <li><%= link_to 'Удалить',  cabinet_destroy_path(@ts), method: :delete, data: { confirm: 'Вы уверены? Ваш сервер будет полностью удален без возврата средств!' }, class: 'btn btn-danger' %></li>
  </ul>
</div>
  </div>


  <div class="col-md-6">

  <div class="tsstatus">
  <% panel = panel_gen.to_s.force_encoding("UTF-8") %>
  <%= @count_users %>/<%= @info['virtualserver_maxclients'] %> <br>
  <%= raw panel%>
  </div>

<!--<div class="tsinfo">-->
  <!--Uptime: <%= Time.at(@info['virtualserver_uptime'].to_i).strftime("%-d:%H:%M:%S") %> <br>-->
<!-- Packet loss: <%= @info['virtualserver_total_packetloss_total'] %> -->
<!--</div>-->

  </div>


</div>

app/views/cabinet/pay.html.erb
<div class="row">
  <div class="col-md-3 col-lg-2 col-sm-5">
    <%= form_tag cabinet_pay_redirect_path, method: :get do %>
        <p>Сумма:</p>
        <div class="form-group">
      <%= number_field_tag :money, 10, min: 5, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= submit_tag 'Пополнить', class: 'btn btn-default' %>
    </div>
    <% end %>
  </div>

</div>

app/views/cabinet/settings.html.erb
<h2>Настройки</h2>

<div>
  <%= form_tag cabinet_settings_edit_path, method: :post do %>
      <%= label_tag 'Название сервера' %> <br>
      <%= text_field_tag  :name, @name %><br>
      <%= label_tag 'Сообщение приветствия' %><br>
      <%= text_area_tag :welcome_message, @welcome_message, style:"margin: 0px; width: 300px; height: 300px;" %><br>
      <%= label_tag 'Пароль' %><br>
      <%= text_field_tag :pass %><br>
      <%= hidden_field_tag :id, params[:id] %>
      <%= submit_tag 'Сохранить' %><br>

  <% end %>
</div>

<%= link_to 'Назад', cabinet_panel_path(@ts.id), class: "btn btn-primary"  %>

app/views/cabinet/token.html.erb
<h2>Список токенов</h2>

<%= form_tag cabinet_create_token_path, method: :post do %>

    <table><tr>
      <td><%= select_tag :group_id, options_for_select(@groups), class: 'select_group' %></td>
      <td><%= text_field_tag :description %></td>
      <td><%= hidden_field_tag :id, @ts.id %></td>
      <td><%= submit_tag 'Создать' %></td>
    </tr></table>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th>Токен</th>
    <th>Описание</th>

  </tr>
  </thead>
  <% @tokens.each do |t|%>
  <tbody><% break if t['token'].blank? %>
      <tr>
        <td><%= t["token"].force_encoding("UTF-8") %></td>
        <td><%= t["token_description"].force_encoding("UTF-8") unless t["token_description"].blank? %></td>

        <td> <%= link_to 'Удалить', {controller: 'cabinet', action: 'delete_token', token: t["token"].force_encoding("UTF-8"), id: @ts.id}, method: :post  %> </td>


      </tr>
  <% end %>
  </tbody>
</table>


<%= link_to 'Назад', cabinet_panel_path(@ts.id), class: "btn btn-primary"  %>