config/routes.rb
Rails.application.routes.draw do


  class WalletoneMiddleware < Walletone::Middleware::Base
    def perform notify, env
      raise 'Wrong signature' unless notify.valid? Settings.w1.signature
        u = User.find(notify.WMI_DESCRIPTION.to_i)
        u.money = u.money+notify.WMI_PAYMENT_AMOUNT.to_i
        pay=Payment.new user_id: notify.WMI_DESCRIPTION.to_i, amount: notify.WMI_PAYMENT_AMOUNT.to_f, order_id: notify.fetch(:WMI_ORDER_ID)
        if pay.valid? and u.valid?
          pay.save!
          u.save!
          'Return some message for OK response'
        else
         raise 'Not saved'
        end
    end
  end

  # match '*path', via: :all, to: 'home#error_404'
  mount WalletoneMiddleware.new => '/w1_callback'

  # scope :unitpay do
  #   get :success, to: 'unitpay#success'
  #   get :fail, to: 'unitpay#fail'
  #   get :notify, to: 'unitpay#notify'
  # end

  post 'cabinet/edit_auto_extension', to: 'cabinet#edit_auto_extension', as: 'cabinet_edit_auto_extension'
  post 'cabinet/free_dns', to: 'cabinet#free_dns', as: 'cabinet_free_dns'
  get 'cabinet/pay', to: 'cabinet#pay', as: 'cabinet_pay'
  get 'cabinet/new', to: 'cabinet#new', as: 'cabinet_new'
  post 'cabinet/create', to: 'cabinet#create', as: 'cabinet_create'
  delete 'cabinet/:id', to: 'cabinet#destroy', as: 'cabinet_destroy'
  get 'cabinet', to: 'cabinet#home', as: 'cabinet_home'
  get 'cabinet/extend/:id', to: 'cabinet#extend', as: 'cabinet_extend'
  post 'cabinet/extend_up/:id', to: 'cabinet#extend_up'
  post 'cabinet/work/:id', to: 'cabinet#work', as: 'cabinet_work'
  get 'cabinet/edit/:id', to: 'cabinet#edit', as: 'cabinet_edit'
  post 'cabinet/update/:id', to: 'cabinet#update', as: 'cabinet_update'
  get 'cabinet/backups/:id', to: 'cabinet#backups', as: 'cabinet_backups'
  post 'cabinet/create_backup'
  post 'cabinet/delete_backup'
  post 'cabinet/apply_backup'
  get 'cabinet/token/:id', to: 'cabinet#token', as: 'cabinet_token'
  post 'cabinet/create_token', to: 'cabinet#create_token', as: 'cabinet_create_token'
  post 'cabinet/delete_token', to: 'cabinet#delete_token', as: 'cabinet_delete_token'
  post 'cabinet/reset_permissions/:id', to: 'cabinet#reset_permissions', as: 'cabinet_reset_permissions'
  get 'cabinet/settings/:id', to: 'cabinet#settings', as: 'cabinet_settings'
  post 'cabinet/settings_edit', to: 'cabinet#settings_edit', as: 'cabinet_settings_edit'
  # get 'cabinet/bans/:id', to: 'cabinet#bans', as: 'cabinet_bans'
  # post 'cabinet/ban', to: 'cabinet#ban', as: 'cabinet_ban'
  # post 'cabinet/unban', to: 'cabinet#unban', as: 'cabinet_unban'
  # post 'cabinet/unbanall', to: 'cabinet#unbanall', as: 'cabinet_unbanall'
  get 'cabinet/pay_redirect', to: 'cabinet#pay_redirect', as: 'cabinet_pay_redirect'
  get 'cabinet/ref', to: 'cabinet#ref', as: 'cabinet_ref'
  get 'cabinet/panel/:id', to: 'cabinet#panel', as: 'cabinet_panel'

  match '/ref/:ref' => 'home#ref', via: [:get, :post]
  get 'admin/info/:id', to: 'admin#info', as: 'admin_info'
  get 'admin/home'
  post 'admin/setmoney/:id', to: 'admin#setmoney'
  get 'admin/belongs_verification', to: 'admin#belongs_verification', as: 'admin_belongs_verification'
  get 'admin/user_list', to: 'admin#user_list', as: 'admin_user_list'
  get 'admin/servers', to: 'admin#servers', as: 'admin_servers'
  get 'admin/del_physical_server', to: 'admin#del_physical_server', as: 'admin_del_physical_server'
  get 'admin/amounts', to: 'admin#amounts', as: 'admin_amounts'
  post 'admin/destroy_payment', to: 'admin#destroy_payment', as: 'admin_destroy_payment'
  get 'admin/panel_tsserver/:id', to: 'admin#panel_tsserver', as: 'admin_panel_tsserver'
  post 'admin/update_panel_tsserver', to: 'admin#update_panel_tsserver', as: 'admin_update_panel_tsserver'


  root 'home#index'
  get '/home/regulations' => 'home#regulations', as: 'home_regulations'
  get 'home/index'
  get 'home/news'
  get '/home/how_buy' => 'home#how_buy', as: 'home_how_buy'

  devise_for :users, :controllers => {registrations: "registrations", passwords: "passwords", sessions: "sessions", omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
  <div class="container">

    <div class="row footerlinks">

      <div class="col-xs-4">


        <ul>
          <li><p>СОЦ СЕТИ</p></li>
          <li><a href="https://vk.com/easy_ts3" target="_blank">Группа в ВК</a></li>
        </ul>

      </div>

      <div class="col-sm-4">

        <ul>
          <li><p>EASY-TS.ru</p></li>
          <li><a href="https://vk.com/easy_ts3" target="_blank">О нас</a></li>
          <li><a href="https://metrika.yandex.ru/stat/?id=44505961&amp;from=informer"
                 target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/44505961/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
                                                     style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" class="ym-advanced-informer" data-cid="44505961" data-lang="ru" /></a>
          </li>
        </ul>
      </div>

      <div class="col-sm-4">
        <ul>
          <li><p>Правила</p></li>
          <li><%= link_to "Пользовательское соглашение", home_regulations_path %></li>
        </ul>
      </div>

    </div>

    <div class="row copyright">
      <p>Copyright © 2017 easy-ts.ru</p>
    </div>



  </div>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
    <% if admin? %>
        <li><%= link_to "Админ панель", admin_home_path %></li>
    <% end %>
  <li><%= link_to "Личный кабинет", cabinet_home_path %></li>
  <li><%= link_to 'Выход', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Вход', new_user_session_path %></li>
  <li><%= link_to 'Регистрация', new_user_registration_path %></li>
 <!-- <li><%= link_to 'Забыли пароль?', new_user_password_path %></li> -->
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Главная', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to "Новости", home_news_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="turbolinks-cache-control" content="no-cache">
    <title>easy-ts | Аренда выделенных серверов TeamSpeak 3</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>




  </head>




  <body>


  <!-- Yandex.Metrika counter -->
  <script type="text/javascript">
      (function (d, w, c) {
          (w[c] = w[c] || []).push(function() {
              try {
                  w.yaCounter44505961 = new Ya.Metrika({
                      id:44505961,
                      clickmap:true,
                      trackLinks:true,
                      accurateTrackBounce:true,
                      webvisor:true
                  });
              } catch(e) { }
          });

          var n = d.getElementsByTagName("script")[0],
              s = d.createElement("script"),
              f = function () { n.parentNode.insertBefore(s, n); };
          s.type = "text/javascript";
          s.async = true;
          s.src = "https://mc.yandex.ru/metrika/watch.js";

          if (w.opera == "[object Opera]") {
              d.addEventListener("DOMContentLoaded", f, false);
          } else { f(); }
      })(document, window, "yandex_metrika_callbacks");
  </script>
  <noscript><div><img src="https://mc.yandex.ru/watch/44505961" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

  <!-- Yandex.Metrika counter -->


  <script src='https://www.google.com/recaptcha/api.js'></script>
    <!-- VK Widget -->
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?136"></script>
    <div id="vk_community_messages"></div>
    <script type="text/javascript">
            VK.Widgets.CommunityMessages("vk_community_messages", 126399695, {});

    </script>
    <!-- VK END -->

    <header>
      <%= render 'layouts/navigation' %>
    </header>


    <main role="main" class="container main clearfix" id="wrap">
      <% flash.each do |name, message| %>
          <div class="alert alert-<%= name %>">
            <%= message %>
          </div>
      <% end %>

      <%= yield %>

    </main>


    <!-- VK Widget -->
     <!-- <div id="vk_groups" class="hidden-xs hidden-sm">-->
     <!--   <script type="text/javascript">-->
     <!--           VK.Widgets.Group("vk_groups", {mode: 4, width: "220", height: "400", color1: 'F4F4F2', color2: '120C0C'}, 126399695);-->
    <!--   </script>-->
     <!--</div>-->


    <div class="footer">
      <%= render 'layouts/footer' %>
    </div>

  </body>

</html>